In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("teen_mental_health.csv")

In [4]:
df

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,mental_health_risk_score,sleep_quality,digital_wellbeing_flag
0,14,male,7.9,Facebook,7.4,2.9,3.01,1.5,low,2,2,1,0,5,Fair,At Risk
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,19,Good,Moderate
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,8,Fair,Healthy
3,15,male,7.4,YouTube,6.9,1.6,3.48,0.8,medium,1,7,9,0,17,Fair,Moderate
4,15,female,4.7,All Platforms,4.9,3.0,2.37,1.4,medium,3,5,2,0,10,Poor,Moderate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0,11,Fair,At Risk
1196,16,male,2.3,All Platforms,8.0,1.9,2.12,0.4,high,7,4,4,0,15,Good,Healthy
1197,14,female,1.7,All Platforms,8.7,0.7,3.98,0.8,high,1,1,1,0,3,Good,Healthy
1198,15,male,3.9,All Platforms,8.5,2.1,3.19,0.6,high,7,9,9,0,25,Good,Moderate
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0,15,Fair,Moderate

In [6]:
df.head(10)

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,mental_health_risk_score,sleep_quality,digital_wellbeing_flag
0,14,male,7.9,Facebook,7.4,2.9,3.01,1.5,low,2,2,1,0,5,Fair,At Risk
1,19,female,1.9,TikTok,8.0,2.9,3.22,0.8,high,8,1,10,0,19,Good,Moderate
2,17,female,1.3,Instagram,7.6,0.5,3.92,0.0,high,2,4,2,0,8,Fair,Healthy
3,15,male,7.4,YouTube,6.9,1.6,3.48,0.8,medium,1,7,9,0,17,Fair,Moderate
4,15,female,4.7,All Platforms,4.9,3.0,2.37,1.4,medium,3,5,2,0,10,Poor,Moderate
5,19,female,7.4,All Platforms,4.4,2.4,2.63,0.6,high,3,5,7,0,15,Poor,At Risk
6,18,female,2.5,Instagram,6.4,2.4,2.63,0.7,low,2,2,5,0,9,Fair,Moderate
7,16,male,4.0,All Platforms,4.2,0.5,2.40,1.3,low,6,10,5,0,21,Poor,Moderate
8,19,female,3.3,YouTube,5.0,2.1,2.04,0.9,high,1,10,9,0,20,Poor,Moderate
9,15,male,1.9,TikTok,4.9,1.5,3.77,1.1,high,1,1,4,0,6,Poor,Healthy

In [7]:
df.tail()

,age,gender,daily_social_media_hours,platform_usage,sleep_hours,screen_time_before_sleep,academic_performance,physical_activity,social_interaction_level,stress_level,anxiety_level,addiction_level,depression_label,mental_health_risk_score,sleep_quality,digital_wellbeing_flag
1195,18,female,6.8,Instagram,6.6,2.0,2.76,1.0,low,3,4,4,0,11,Fair,At Risk
1196,16,male,2.3,All Platforms,8.0,1.9,2.12,0.4,high,7,4,4,0,15,Good,Healthy
1197,14,female,1.7,All Platforms,8.7,0.7,3.98,0.8,high,1,1,1,0,3,Good,Healthy
1198,15,male,3.9,All Platforms,8.5,2.1,3.19,0.6,high,7,9,9,0,25,Good,Moderate
1199,16,female,4.7,TikTok,6.5,1.0,2.91,0.9,medium,5,7,3,0,15,Fair,Moderate

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   age                       1200 non-null   int64
 1   gender                    1200 non-null   str
 2   daily_social_media_hours  1200 non-null   float64
 3   platform_usage            1200 non-null   str
 4   sleep_hours               1200 non-null   float64
 5   screen_time_before_sleep  1200 non-null   float64
 6   academic_performance      1200 non-null   float64
 7   physical_activity         1200 non-null   float64
 8   social_interaction_level  1200 non-null   str
 9   stress_level              1200 non-null   int64
 10  anxiety_level             1200 non-null   int64
 11  addiction_level           1200 non-null   int64
 12  depression_label          1200 non-null   int64
 13  mental_health_risk_score  1200 non-null   int64
 14  sleep_quality             1200 non-null   str
 15  digital_wellbeing_flag    1200 non-null   str
dtypes: float64(5), int64(6), str(5)
memory usage: 150.1 KB

In [11]:
df.isnull().sum()

age                         0
gender                      0
daily_social_media_hours    0
platform_usage              0
sleep_hours                 0
screen_time_before_sleep    0
academic_performance        0
physical_activity           0
social_interaction_level    0
stress_level                0
anxiety_level               0
addiction_level             0
depression_label            0
mental_health_risk_score    0
sleep_quality               0
digital_wellbeing_flag      0
dtype: int64